### ISSUE TITLE
/etc/cloudflared creation is not idempotent

### ISSUE THREAD

**Issue by qdd-gh** [papanito/ansible-role-cloudflared#48]
In `tasks/install.yml`, the `/etc/cloudflared` directory is checked/created with mode `0744`, while in `tasks/configure_tunnels.yml` it is given mode `0755`. This forces a change every time the role is used, and prevents it from being idempotent.

**Comment by papanito** [comment]
Thanks for the issue

**Comment by papanito** [comment]
FYI, I made a new release v3.6.1
